version: "3.4"

services:
  identity.service:
    depends_on:
      - db
    image: identity-service
    container_name: identity.service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:4567 # Puerto de App de salida configurable
    environment:
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  db:
    image: postgres:15.8-alpine
    container_name: identity.db
    restart: always
    ports:
      - "${DB_PORT}:5432" # Puerto de BD de salida configurable
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data # Bind mount para persistencia de datos
      - ./scripts:/docker-entrypoint-initdb.d # Carpeta con scripts de inicializaci√≥n
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  flyway:
    image: flyway/flyway:11.18.0-alpine
    container_name: flyway
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${DB_NAME}
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_BASELINE_ON_MIGRATE: "true" # Crea la flwyway_schema_history si no existe
    volumes:
      - ./migrations:/flyway/sql
    command: -connectRetries=10 migrate
